[swipe.commands.three]
left_up = ""
right_up = ""
up = "xdotool key Super_L+w"
left_down = ""
right_down = ""
down = "xdotool key ctrl+F12"
# for x11
left = "xdotool key ctrl+shift+Tab"
right = "xdotool key ctrl+Tab"
# for wayland
# left = "wtype -M ctrl -M shift -P tab -p tab -m shift -m ctrl"
# right = "wtype -M ctrl -P tab -p tab -m ctrl"

[swipe.commands.four]
left_up = ""
right_up = ""
up = ""
left_down = ""
right_down = ""
down = ""
left = "xdotool key alt+shift+Tab"
right = "xdotool key alt+Tab"

[pinch.commands]
in = ""
out = ""

[pinch.settings]
threshold = 0.25
one_shot = false


[swipe.settings]
threshold = 0.5
one_shot = true
trigger_on_release = false
