# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "relatime" "mode=755" ];
  };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/534bb3c0-76f6-4dd8-acfb-63a0c5121ab5";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DA15-1004";
      fsType = "vfat";
    };

  fileSystems."/getea" =
    { device = "/dev/disk/by-uuid/ac8fd036-2dc5-4ed4-83b1-56aecb478522";
      fsType = "btrfs";
      options = [ "compress=zstd" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/daf9166d-eda8-4130-a859-d28b171bf8d8"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
